all:
	gcc -std=gnu99 -c main.c
	gcc -std=gnu99 -c teacher.c
	gcc -std=gnu99 -c display.c
	gcc -std=gnu99 -c password.c
	gcc -std=gnu99 -c tea_inf_func.c
	gcc -std=gnu99 -c tea_ach_func.c
	gcc -std=gnu99 -c student.c
	gcc -std=gnu99 -c adm.c
	gcc -std=gnu99 -c super_adm.c
	gcc -std=gnu99 -c get_cmd.c
	gcc main.o teacher.o display.o password.o  tea_inf_func.o tea_ach_func.o  student.o adm.o super_adm.o get_cmd.o -o system
